// Autogenerated file by build.py, don't change!

package org.renpy.android;

public class Configuration {
	{% if args.billing_pubkey %}
	static public boolean use_billing = true;
	static public String billing_pubkey = "{{ args.billing_pubkey }}";
	{% else %}
	static public boolean use_billing = false;
	static public String billing_pubkey = null;
	{% endif %}
	static public byte billing_salt[] = new byte[] {41, -90, -116, -41, 66, -53, 122, -110, -127, -96, -88, 77, 127, 115, 1, 73, 57, 110, 48, -116};
}
