#:import FONT_SIZE_SUBTITLE constants.FONT_SIZE_SUBTITLE
#:import FONT_SIZE_TEXT constants.FONT_SIZE_TEXT
#:import FONT_SIZE_TITLE constants.FONT_SIZE_TITLE

#:import set_device_orientation tools.set_device_orientation
#:import Spacer20 widgets.Spacer20
#:import CircularButton widgets.CircularButton

#:set green_color (0.3, 0.5, 0, 1)
#:set red_color (1.0, 0, 0, 1)

<ScreenWorker@Screen>:
    name: 'worker'
    ScrollView:
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None
            height: self.minimum_height
            Button:
                text: 'Back to unittests'
                font_size: sp(FONT_SIZE_SUBTITLE)
                size_hint_y: None
                height: dp(60)
                on_press: root.parent.current = 'unittests'
            Image:
                keep_ratio: False
                allow_stretch: True
                source: 'static/coloursinv.png'
                size_hint_y: None
                height: dp(100)
            Label:
                text:
                    '[color=#999999]Test[/color] P4A ' \
                    '[color=#999999]service[/color]'
                size_hint_y: None
                padding: 0, 20
                height: self.texture_size[1]
                halign: 'center'
                font_size: sp(FONT_SIZE_TITLE)
                font_name: 'static/Blanka-Regular.otf'
                text_size: root.width, None
                markup: True
            Spacer20:
            Spacer20:
            RelativeLayout:
                size_hint_y: None
                height: dp(100)
                CircularButton:
                    text: 'Start Worker' if not app.work.running else 'Stop Worker'
                    pos_hint: {'center_x': .5}
                    background_color: red_color if not app.work.running else green_color
                    on_press: app.worker_button_pressed()
            Spacer20:
            Spacer20:
            ProgressBar:
                pos_hint: {'center_x': .5}
                size_hint_x: .5
                size_hint_y: None
                value: app.work.progress
            Label:
                text: 'Work state: ' + app.work.state
                size_hint_y: None
                height: self.texture_size[1]
                halign: 'center'
                text_size: root.width, None
                font_size: sp(FONT_SIZE_TEXT)
            Spacer20:
            Spacer20:
            Label:
                text:
                    '[color=#ff5900]WARNING:[/color] ' \
                    'this test only works on an Android device'
                markup: True
                size_hint_y: None
                height: self.texture_size[1]
                halign: 'center'
                text_size: root.width, None
                font_size: sp(FONT_SIZE_TEXT)
