LOCAL_PATH := $(call my-dir)/..

include $(CLEAR_VARS)
LOCAL_MODULE            := sqlite3
LOCAL_SRC_FILES         := sqlite3.c
LOCAL_CFLAGS            := -DSQLITE_ENABLE_FTS3
# ALL TESTS WITH THREAD SAFE ENABLED ARE
# NOT WORKING AS EXPECTED SO...DISABLED FOR NOW.
# LOCAL_CFLAGS            += -DSQLITE_THREADSAFE=1
include $(BUILD_SHARED_LIBRARY)
