LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := sdl_blitpool

LOCAL_CFLAGS := -I$(LOCAL_PATH) -I$(LOCAL_PATH)/../sdl/include

LOCAL_CPP_EXTENSION := .cpp

LOCAL_SRC_FILES := SDL_blitpool.c

LOCAL_SHARED_LIBRARIES := sdl
LOCAL_STATIC_LIBRARIES :=
LOCAL_LDLIBS :=

LOCAL_CFLAGS += $(REDIRECT_CFLAGS)
LOCAL_LDFLAGS += $(REDIRECT_LDFLAGS)

include $(BUILD_SHARED_LIBRARY)

