LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := mad

LOCAL_CFLAGS := -I$(LOCAL_PATH) \
					-DFPM_64BIT -DOPT_SPEED \
					-DSTDC_HEADERS -DHAVE_UNISTD_H \
					-DSIZEOF_INT=4 -DSIZEOF_LONG=4 -DSIZEOF_LONG_LONG=8 \
					-DHAVE_ASSERT_H -DHAVE_ERRNO_H -DHAVE_FCNTL_H -DHAVE_INTTYPES_H \
					-DHAVE_LIMITS_H -DHAVE_MEMORY_H -DHAVE_STDINT_H -DHAVE_STDLIB_H \
					-DHAVE_STRINGS_H -DHAVE_STRING_H -DHAVE_SYS_STAT_H -DHAVE_SYS_TYPES_H

LOCAL_CPP_EXTENSION := .cpp

LOCAL_SRC_FILES := $(notdir $(wildcard $(LOCAL_PATH)/*.c))

LOCAL_SHARED_LIBRARIES := 

include $(BUILD_SHARED_LIBRARY)

