# When a user creates an issue that is actually a support request, it should
# be closed with a friendly comment.
#
# This triggers on an issue being labelled with the `support` tag.

name: 'Support Requests'

on:
  issues:
    types: [labeled, unlabeled, reopened]

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v4
        with:
          github-token: ${{ github.token }}
          support-label: 'support'
          issue-comment: >
            👋 @{issue-author},
            
            Sorry to hear you are having difficulties with Kivy's python-for-android; Kivy unites a number of different technologies, so building apps can be temperamental.

            We try to use GitHub issues only to track work for developers to do to fix bugs and add new features to python-for-android. 
            
            However, this issue appears to be a support request. Please use our
            [support channels](https://github.com/kivy/python-for-android/blob/master/CONTACT.md)
            to get help with the project.

            If you're having trouble installing python-for-android,
            please see our [quickstart](https://python-for-android.readthedocs.io/en/latest/quickstart) guide.

            If you're having trouble using python-for-android,
            please see our [troubleshooting guide](https://python-for-android.readthedocs.io/en/latest/troubleshooting) 
            and [FAQ](https://github.com/kivy/python-for-android/blob/master/FAQ.md).

            Let us know if this comment was made in error, and we'll be happy
            to reopen the issue.

          close-issue: true
          lock-issue: false
